# Generated by Django 4.0.2 on 2022-02-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_accountant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.PositiveIntegerField(default=20000, null=True),
        ),
    ]
