# Generated by Django 4.0.2 on 2022-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_alter_course_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemanager',
            name='to_acno',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
